export const dummyAlumni = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+91 98765 43210',
    branch: 'CSE',
    batch: '2015',
    position: 'Senior Software Engineer',
    company: 'Google',
    location: 'Bangalore, India',
    skills: ['React', 'Node.js', 'Python', 'AWS', 'Docker'],
    linkedin: 'https://linkedin.com/in/johndoe',
    achievements: ['Published 5 research papers', 'Won Best Alumni Award 2023'],
    about: 'Passionate software engineer with 8+ years of experience.',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    branch: 'ECE',
    batch: '2016',
    position: 'Product Manager',
    company: 'Microsoft',
    location: 'Seattle, USA',
    skills: ['Product Management', 'Agile', 'Data Analysis'],
    linkedin: 'https://linkedin.com/in/janesmith',
  },
  {
    id: '3',
    name: 'Mike Johnson',
    email: 'mike.johnson@example.com',
    branch: 'EEE',
    batch: '2014',
    position: 'Data Scientist',
    company: 'Amazon',
    location: 'Hyderabad, India',
    skills: ['Machine Learning', 'Python', 'TensorFlow', 'SQL'],
  },
  {
    id: '4',
    name: 'Sarah Williams',
    email: 'sarah.williams@example.com',
    branch: 'ME',
    batch: '2017',
    position: 'Mechanical Engineer',
    company: 'Tesla',
    location: 'California, USA',
    skills: ['CAD', 'SolidWorks', 'Project Management'],
  },
  {
    id: '5',
    name: 'David Brown',
    email: 'david.brown@example.com',
    branch: 'CE',
    batch: '2013',
    position: 'Civil Engineer',
    company: 'L&T',
    location: 'Mumbai, India',
    skills: ['Structural Design', 'AutoCAD', 'Project Planning'],
  },
]

export const dummyJobs = [
  {
    id: '1',
    title: 'Senior Software Engineer',
    company: 'Google',
    location: 'Bangalore, India',
    salary: '₹25-40 LPA',
    type: 'Full-time',
    posted: '2 days ago',
    description: 'We are looking for an experienced software engineer to join our team...',
    requirements: ['5+ years experience', 'Strong in React and Node.js', 'Good problem-solving skills'],
    skills: ['React', 'Node.js', 'JavaScript', 'AWS'],
  },
  {
    id: '2',
    title: 'Product Manager',
    company: 'Microsoft',
    location: 'Seattle, USA',
    salary: '$120k-150k',
    type: 'Full-time',
    posted: '5 days ago',
    description: 'Lead product development for our cloud services platform...',
    requirements: ['MBA preferred', '5+ years PM experience', 'Strong analytical skills'],
    skills: ['Product Management', 'Agile', 'Data Analysis'],
  },
  {
    id: '3',
    title: 'Data Scientist',
    company: 'Amazon',
    location: 'Hyderabad, India',
    salary: '₹20-35 LPA',
    type: 'Full-time',
    posted: '1 week ago',
    description: 'Work on machine learning models for recommendation systems...',
    requirements: ['PhD or Masters in CS', 'Experience with ML frameworks', 'Python expertise'],
    skills: ['Machine Learning', 'Python', 'TensorFlow', 'SQL'],
  },
]

export const dummyEvents = [
  {
    id: '1',
    title: 'Alumni Reunion 2026',
    description: 'Join us for the annual alumni reunion. Connect with old friends and make new connections.',
    date: '2026-03-15',
    time: '6:00 PM',
    location: 'College Campus',
    attendees: 250,
    banner: null,
  },
  {
    id: '2',
    title: 'Tech Talk: AI in Industry',
    description: 'Expert panel discussion on the latest trends in artificial intelligence and machine learning applications.',
    date: '2026-02-20',
    time: '4:00 PM',
    location: 'Virtual - Zoom',
    attendees: 180,
  },
  {
    id: '3',
    title: 'Networking Mixer 2026',
    description: 'An evening of networking with alumni from various industries. Expand your professional circle.',
    date: '2026-02-05',
    time: '7:00 PM',
    location: 'City Hotel Convention Center',
    attendees: 150,
  },
  {
    id: '4',
    title: 'Entrepreneurship Workshop',
    description: 'Learn from successful alumni entrepreneurs about starting and scaling your business.',
    date: '2026-04-10',
    time: '10:00 AM',
    location: 'Innovation Hub',
    attendees: 95,
  },
  {
    id: '5',
    title: 'Sports Tournament 2026',
    description: 'Annual inter-batch sports tournament featuring cricket, football, and badminton.',
    date: '2026-05-22',
    time: '8:00 AM',
    location: 'College Sports Complex',
    attendees: 320,
  },
  {
    id: '6',
    title: 'Cultural Festival',
    description: 'Celebrate diversity with performances, food stalls, and cultural exhibitions.',
    date: '2026-06-15',
    time: '5:00 PM',
    location: 'College Auditorium',
    attendees: 400,
  },
  {
    id: '7',
    title: 'Career Mentorship Program Launch',
    description: 'Kickoff event for our new mentorship program connecting students with alumni professionals.',
    date: '2026-01-25',
    time: '3:00 PM',
    location: 'Virtual - Google Meet',
    attendees: 200,
  },
  {
    id: '8',
    title: 'Alumni Awards Gala',
    description: 'Evening gala honoring outstanding alumni achievements in various fields.',
    date: '2026-07-20',
    time: '7:30 PM',
    location: 'Grand Ballroom, Downtown',
    attendees: 280,
  },
  {
    id: '9',
    title: 'Hackathon 2026',
    description: '24-hour coding challenge with prizes and mentorship from industry experts.',
    date: '2026-03-28',
    time: '9:00 AM',
    location: 'College Tech Lab',
    attendees: 120,
  },
  {
    id: '10',
    title: 'Leadership Summit',
    description: 'Interactive sessions with industry leaders discussing leadership best practices and career growth.',
    date: '2026-08-15',
    time: '2:00 PM',
    location: 'Conference Center',
    attendees: 175,
  },
  {
    id: '11',
    title: 'Alumni Golf Tournament',
    description: 'Annual charity golf tournament. All proceeds go to student scholarships.',
    date: '2026-09-10',
    time: '7:00 AM',
    location: 'Greenwood Golf Club',
    attendees: 80,
  },
  {
    id: '12',
    title: 'Innovation & Startup Expo',
    description: 'Showcase of alumni-led startups and innovation projects. Networking and investment opportunities.',
    date: '2026-10-05',
    time: '11:00 AM',
    location: 'Tech Park Exhibition Hall',
    attendees: 220,
  },
  {
    id: '13',
    title: 'Alumni Book Club Meetup',
    description: 'Monthly virtual book discussion featuring business and leadership books.',
    date: '2026-01-30',
    time: '7:00 PM',
    location: 'Virtual - Microsoft Teams',
    attendees: 45,
  },
  {
    id: '14',
    title: 'Wellness & Yoga Retreat',
    description: 'Weekend wellness retreat focusing on mental health, yoga, and mindfulness.',
    date: '2026-04-25',
    time: '9:00 AM',
    location: 'Mountain View Resort',
    attendees: 60,
  },
  {
    id: '15',
    title: 'Career Development Workshop',
    description: 'Learn about career growth strategies and networking tips from HR professionals.',
    date: '2024-01-10',
    time: '10:00 AM',
    location: 'College Auditorium',
    attendees: 120,
  },
  {
    id: '16',
    title: 'Homecoming Weekend 2023',
    description: 'Three-day celebration with campus tours, alumni meet-ups, and special presentations.',
    date: '2023-12-01',
    time: '9:00 AM',
    location: 'College Campus',
    attendees: 450,
  },
  {
    id: '17',
    title: 'Industry Connect 2023',
    description: 'Job fair connecting students with alumni-led companies and recruiters.',
    date: '2023-11-15',
    time: '11:00 AM',
    location: 'Exhibition Hall',
    attendees: 350,
  },
]

export const dummyStories = [
  {
    id: '1',
    name: 'Dr. Rajesh Kumar',
    position: 'Chief Technology Officer',
    company: 'TechCorp India',
    branch: 'Computer Science',
    batch: '2005',
    location: 'Bangalore, India',
    story: 'My journey from a small-town student to CTO has been nothing short of remarkable. Starting as a junior developer right after graduation, I faced numerous challenges and setbacks. However, the strong technical foundation and problem-solving skills I developed at LPU helped me navigate through tough times. I made it a point to never stop learning - completing certifications, attending tech conferences, and contributing to open-source projects. After 5 years of dedication, I became a team lead, then engineering manager, and finally CTO. Today, I lead a team of 200+ brilliant engineers building products that impact millions of users worldwide.',
    achievements: ['Led team of 200+ engineers', 'Launched 10+ successful products', 'Mentored 50+ students', 'Speaker at international tech conferences'],
    link: 'https://linkedin.com/in/rajeshkumar',
  },
  {
    id: '2',
    name: 'Dr. Priya Sharma',
    position: 'Research Scientist',
    company: 'MIT',
    branch: 'Electronics & Communication',
    batch: '2010',
    location: 'Boston, USA',
    story: 'My passion for signal processing and AI started in the labs at LPU. What began as curiosity about how machines could learn evolved into groundbreaking research at MIT. During my PhD, I focused on developing novel algorithms for real-time signal processing in medical devices. The breakthrough came when our team developed a system that could predict cardiac events 30 minutes before they occur. This research has saved countless lives and earned recognition from the global medical community. I credit my success to the research-oriented mindset instilled during my undergraduate years.',
    achievements: ['Published 25+ papers in top-tier journals', 'Received Best Researcher Award 2023', 'Holder of 3 patents', 'TED speaker'],
    link: 'https://linkedin.com/in/priyasharma',
  },
  {
    id: '3',
    name: 'Arjun Malhotra',
    position: 'Founder & CEO',
    company: 'FinNext Solutions',
    branch: 'Information Technology',
    batch: '2012',
    location: 'San Francisco, USA',
    story: 'The entrepreneurial spirit I developed at LPU led me to start my own fintech company. We began in a small garage with just 3 people and a vision to democratize financial services. Five years later, FinNext Solutions has grown to over 500 employees and processes billions in transactions annually. Our mobile app has helped over 10 million users access affordable financial services. The journey wasn\'t easy - we faced funding challenges, regulatory hurdles, and fierce competition. But the resilience and innovative thinking I learned during my college years kept me going.',
    achievements: ['Built $500M+ valued company', 'Raised $150M in funding', '10M+ active users', 'Forbes 30 Under 30'],
    link: 'https://linkedin.com/in/arjunmalhotra',
  },
  {
    id: '4',
    name: 'Sneha Patel',
    position: 'Vice President, Product',
    company: 'Amazon Web Services',
    branch: 'Computer Science',
    batch: '2013',
    location: 'Seattle, USA',
    story: 'Starting as a product management intern at a small startup, I learned the importance of customer obsession and data-driven decision making. These principles, combined with the technical skills from LPU, helped me transition to Amazon. Over the years, I\'ve led product initiatives that generated over $2B in revenue. What I love most is mentoring young product managers and watching them grow. The collaborative projects and team assignments at LPU taught me how to work with diverse teams - a skill that\'s invaluable in today\'s global workplace.',
    achievements: ['Led products generating $2B+ revenue', 'Managed teams across 5 countries', 'Guest lecturer at Stanford', 'Published author'],
    link: 'https://linkedin.com/in/snehapatel',
  },
  {
    id: '5',
    name: 'Vikram Singh',
    position: 'Principal Architect',
    company: 'Netflix',
    branch: 'Computer Science',
    batch: '2008',
    location: 'Los Angeles, USA',
    story: 'My fascination with distributed systems and cloud architecture began during my final year project at LPU. After graduation, I joined a startup where I learned to build scalable systems from scratch. This experience caught Netflix\'s attention, and I joined their infrastructure team. Today, I architect systems that serve 230+ million subscribers worldwide, ensuring they can stream content without interruption. The problem-solving approach and algorithmic thinking skills from my college days form the foundation of my architectural decisions.',
    achievements: ['Designed systems serving 230M+ users', 'Reduced infrastructure costs by 40%', 'Conference speaker', '15+ tech blog posts'],
    link: 'https://linkedin.com/in/vikramsingh',
  },
  {
    id: '6',
    name: 'Ananya Reddy',
    position: 'AI Research Lead',
    company: 'DeepMind',
    branch: 'Computer Science',
    batch: '2014',
    location: 'London, UK',
    story: 'Artificial Intelligence wasn\'t even a popular field when I graduated, but I was fascinated by it. I pursued a PhD focusing on reinforcement learning and natural language processing. My research on making AI systems more interpretable caught DeepMind\'s attention. Now, I lead a team working on AI safety and ethics. We\'re developing systems that can explain their decisions, making AI more trustworthy. The critical thinking and research methodology I learned at LPU gave me the confidence to pursue this cutting-edge field.',
    achievements: ['Leading AI safety research', 'Published 30+ research papers', 'Keynote speaker at NeurIPS', 'Advisory board member'],
    link: 'https://linkedin.com/in/ananyareddy',
  },
  {
    id: '7',
    name: 'Karan Mehta',
    position: 'Director of Engineering',
    company: 'SpaceX',
    branch: 'Mechanical Engineering',
    batch: '2011',
    location: 'California, USA',
    story: 'Working on rockets was always my dream. After graduation, I joined an aerospace startup where I worked on satellite systems. My expertise in propulsion systems and project management led to an opportunity at SpaceX. Today, I oversee the engineering teams working on the Starship project. Seeing something you\'ve worked on launch into space is indescribable. The hands-on experience with projects and the emphasis on practical learning at LPU prepared me for the challenges of aerospace engineering.',
    achievements: ['Contributed to 15+ successful launches', 'Led team of 100+ engineers', 'Innovation Award winner', 'Guest speaker at MIT'],
    link: 'https://linkedin.com/in/karanmehta',
  },
  {
    id: '8',
    name: 'Meera Nair',
    position: 'Managing Director',
    company: 'Goldman Sachs',
    branch: 'Computer Science',
    batch: '2009',
    location: 'New York, USA',
    story: 'My career in finance started unexpectedly when a campus recruiter saw potential in my algorithmic trading project. I joined Goldman Sachs as a quantitative analyst, combining my coding skills with financial knowledge. Over the years, I built trading systems that processed millions of transactions daily. Today, as Managing Director, I lead the tech strategy for our trading division. The ability to learn quickly and adapt - skills I honed during intensive coding sessions at LPU - has been crucial to my success in the fast-paced world of finance.',
    achievements: ['Managing $10B+ in assets', 'Built award-winning trading systems', 'Mentor to 200+ analysts', 'Harvard Business Review contributor'],
    link: 'https://linkedin.com/in/meeranair',
  },
  {
    id: '9',
    name: 'Rohit Sharma',
    position: 'Chief Data Scientist',
    company: 'Uber',
    branch: 'Computer Science',
    batch: '2015',
    location: 'San Francisco, USA',
    story: 'Data science wasn\'t part of our curriculum when I was at LPU, but the strong foundation in programming and statistics helped me transition into this field. I started by taking online courses and working on Kaggle competitions. My winning solution in a major competition got me noticed by Uber. Now, I lead data science initiatives that optimize everything from pricing to driver allocation, impacting millions of rides daily. The self-learning discipline I developed during my college projects has been invaluable.',
    achievements: ['Led ML models serving 100M+ users', 'Kaggle Grandmaster', 'Published ML research', 'AI Conference organizer'],
    link: 'https://linkedin.com/in/rohitsharma',
  },
  {
    id: '10',
    name: 'Divya Krishnan',
    position: 'Co-founder & CTO',
    company: 'HealthTech Innovations',
    branch: 'Biotechnology',
    batch: '2016',
    location: 'Bangalore, India',
    story: 'Combining technology with healthcare has always been my passion. During my final year, I worked on a project using AI for early disease detection. This became the foundation of HealthTech Innovations. Our platform now uses machine learning to analyze medical images, helping doctors detect diseases earlier. We\'ve partnered with 200+ hospitals and our technology has helped diagnose over 500,000 patients. The interdisciplinary approach encouraged at LPU taught me to bridge the gap between technology and healthcare.',
    achievements: ['Served 500K+ patients', 'Raised $50M funding', 'WHO Innovation Award', 'Featured in TIME Magazine'],
    link: 'https://linkedin.com/in/divyakrishnan',
  },
]

